update setup script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 ###     configure system to use networkradius.com binary packages these are newer than those supplied by ubuntu     ###
 #
@@ -9,80 +9,48 @@ if [ ! $UID = 0 ]; then
     exit 1
 fi
 
-if lsb_release -d | awk -F"\t" '{print $2}' | grep -q Ubuntu
-    then
-            if lsb_release -d | awk -F"\t" '{print $2}' | grep -q 20.04
-                then
-                    echo ""
-                    echo "found ubuntu 20.04"
-                    if cat /etc/apt/sources.list | grep -q networkradius
-                        then
-                            echo "networkradius package repo is already present in (/etc/apt/sources.list)"
-                        else
-                            echo "adding networkradius repo (deb https://packages.networkradius.com/releases/ubuntu-focal focal main) to (/etc/apt/sources.list)"
-                            echo 'deb [trusted=yes] https://packages.networkradius.com/releases/ubuntu-focal focal main' >> /etc/apt/sources.list
-                    fi
-            elif lsb_release -d | awk -F"\t" '{print $2}' | grep -q 18.04
-                then
-                    echo ""
-                    echo "found ubuntu 18.04"
-                    if cat /etc/apt/sources.list | grep -q networkradius
-                        then
-                            echo "networkradius package repo is already present in (/etc/apt/sources.list)"
-                        else
-                            echo "adding ( https://packages.networkradius.com/releases/ubuntu-bionic bionic main) to (/etc/apt/sources.list)"
-                            echo 'deb [trusted=yes] https://packages.networkradius.com/releases/ubuntu-bionic bionic main' >> /etc/apt/sources.list
-                    fi
-                    # add additional repo for new php needed for new composer 
-                    if -s /etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list
-                        then
-                            echo "ondrej-ubuntu-php package repo is already present in (/etc/apt/sources.list.d/)"
-                        else
-                            echo "creating the repo file with the address ( http://ppa.launchpad.net/ondrej/php/ubuntu bionic main) to (/etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list)"
-                            echo 'deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main' >> /etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list
-                            echo 'deb-src http://ppa.launchpad.net/ondrej/php/ubuntu bionic main' >> /etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list
-                            
-                            export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
-                            if apt-key list | grep -q ondrej
-                                then 
-                                    echo "the ondrej php repo gpg key was found"
-                                else
-                                    echo "the ondrej php repo gpg key was not found we will add it to the local keyring now "
-                                    apt-key adv --keyserver keyserver.ubuntu.com --recv-key 0xE5267A6C
-                                if apt-key list | grep -q ondrej
-                                then 
-                                    echo "the ondrej php gpg key was added successfully"
-                                else 
-                                    echo "something went wrong while adding the ondrej php gpg key"
-                                fi
-                            fi 
-                    fi
+LSB_RELEASE=$(lsb_release -d | cut -f2)
+if echo $LSB_RELEASE | grep -q 'Ubuntu.*20.04'; then
+    if cat /etc/apt/sources.list | grep -q networkradius; then
+        echo "networkradius package repo is already present in (/etc/apt/sources.list)"
+    else
+        echo "adding networkradius repo (deb https://packages.networkradius.com/releases/ubuntu-focal focal main) to (/etc/apt/sources.list)"
+        echo 'deb [trusted=yes] https://packages.networkradius.com/releases/ubuntu-focal focal main' >> /etc/apt/sources.list
+    fi
+elif echo $LSB_RELEASE | grep -q 'Ubuntu.*18.04'; then
+    if cat /etc/apt/sources.list | grep -q networkradius; then
+        echo "networkradius package repo is already present in (/etc/apt/sources.list)"
+    else
+        echo "adding ( https://packages.networkradius.com/releases/ubuntu-bionic bionic main) to (/etc/apt/sources.list)"
+        echo 'deb [trusted=yes] https://packages.networkradius.com/releases/ubuntu-bionic bionic main' >> /etc/apt/sources.list
+    fi
+    # add additional repo for new php needed for new composer
+    if [ -s /etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list ]; then
+        echo "ondrej-ubuntu-php package repo is already present in (/etc/apt/sources.list.d/)"
+    else
+        echo "creating the repo file with the address ( http://ppa.launchpad.net/ondrej/php/ubuntu bionic main) to (/etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list)"
+        echo 'deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main' >> /etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list
+        echo 'deb-src http://ppa.launchpad.net/ondrej/php/ubuntu bionic main' >> /etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list
+
+        export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
+        if apt-key list | grep -q 'E526 7A6C'
+            then
+                echo "the ondrej php repo gpg key was found"
+            else
+                echo "the ondrej php repo gpg key was not found we will add it to the local keyring now "
+                apt-key adv --keyserver keyserver.ubuntu.com --recv-key 0xE5267A6C
+            if apt-key list | grep -q 'E526 7A6C'
+            then
+                echo "the ondrej php gpg key was added successfully"
+            else
+                echo "something went wrong while adding the ondrej php gpg key"
+                exit 1
             fi
-elif lsb_release -d | awk -F"\t" '{print $2}' | grep -q Debian
-    then
-            if lsb_release -d | awk -F"\t" '{print $2}' | grep -q stretch
-                then
-                    echo ""
-                    echo "found Debian stretch"
-                    if cat /etc/apt/sources.list | grep -q networkradius
-                        then
-                            echo "networkradius package repo is already present in (/etc/apt/sources.list)"
-                        else
-                            echo "adding (deb https://packages.networkradius.com/releases/debian-stretch stretch main) to (/etc/apt/sources.list)"
-                            echo 'deb [trusted=yes] https://packages.networkradius.com/releases/debian-stretch stretch main' >> /etc/apt/sources.list
-                    fi
-            elif lsb_release -d | awk -F"\t" '{print $2}' | grep -q buster
-                then
-                    echo ""
-                    echo "found Debian buster"
-                    if cat /etc/apt/sources.list | grep -q networkradius
-                        then
-                            echo "networkradius package repo is already present in (/etc/apt/sources.list)"
-                        else
-                            echo "adding (deb https://packages.networkradius.com/releases/debian-buster buster main) to (/etc/apt/sources.list)"
-                            echo 'deb [trusted=yes] https://packages.networkradius.com/releases/ubuntu-focal focal main' >> /etc/apt/sources.list
-                    fi
-            fi
+        fi
+    fi
+else
+    echo Sorry, this tool currently only supports Ubuntu 18.04 or 20.04.
+    exit 1
 fi
 
 #
@@ -90,18 +58,17 @@ fi
 #
 
 export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
-if apt-key list | grep -q networkradius
-    then 
+if apt-key list | grep -q networkradius; then
         echo "the networkradius repo gpg key was found"
+else
+    echo "the networkradius repo gpg key was not found we will add it to the local keyring now "
+    apt-key adv --keyserver keyserver.ubuntu.com --recv-key 0x41382202
+    if apt-key list | grep -q '4138 2202'; then
+        echo "the networkradius gpg key was added successfully"
     else
-        echo "the networkradius repo gpg key was not found we will add it to the local keyring now "
-        apt-key adv --keyserver keyserver.ubuntu.com --recv-key 0x41382202
-        if apt-key list | grep -q networkradius
-            then 
-                echo "the networkradius gpg key was added successfully"
-            else 
-                echo "something went wrong while adding the network radius gpg key"
-        fi
+        echo "something went wrong while adding the network radius gpg key"
+        exit 1
+    fi
 fi
 
 #
@@ -113,14 +80,10 @@ apt-get upgrade --yes
 apt-get install --yes php-cli php-mbstring php-mysql php-curl unzip mariadb-server mariadb-client
 apt-cache policy freeradius | grep -q networkradius
 if [ $? = 1 ]; then
-    echo "ERROR"
-    echo ""
-    echo "the apt policy for freeradius would install distribution provided packages!!!"
-    echo "please check/correct the apt config to install the NetworkRADIUS binaries!!!"
-    echo "you can check the policy using the command!!!"
-    echo "apt-cache policy freeradius"
-    echo ""
-    echo ".. exiting due to apt policy mismatch !"
+    echo -e "ERROR:\n"
+    echo "The apt policy for freeradius would install distribution provided packages."
+    echo "Please check/correct the apt config to install the NetworkRADIUS binaries."
+    echo "You can check the policy using the command: 'apt-cache policy freeradius'"
     exit 1
 fi
 
@@ -130,89 +93,73 @@ apt-get install --yes freeradius freeradius-common freeradius-utils freeradius-m
 ###     test for an existing swap device or file, if none exists we will create one     ###
 #
 
-if cat /etc/fstab | grep -q swap
+if cat /etc/fstab | grep -q swap; then
+    echo "swap was found in fstab"
+    if free | grep -qP '^Swap:\s+[0-9]{2,}'; then
+        echo "swap is enabled"
+    else
+        echo "swap was not enabled/sufficient. Enabling now..."
+        swapon -a
+    fi
+else
+    echo "no swap found in fstab we will now create and enable a swapfile"
+    /usr/bin/fallocate -l 4G /swapfile
+    /bin/chmod 600 /swapfile
+    /sbin/mkswap /swapfile
+    /sbin/swapon /swapfile
+    echo '/swapfile none swap sw 0 0' >> /etc/fstab
+fi
+
+#
+###     setup sysctl    ###
+#
+
+if grep -q vm.swappiness /etc/sysctl.conf; then
+    echo "vm.swappiness found in sysctl.conf "
+    if sysctl -a | grep -q swappiness
         then
-                echo "swap was found in fstab"
-                if free | awk '/^Swap:/ {exit !$2}'
-                        then
-                                echo "swap is enabled"
-                        else
-                                echo "swap was not enabled we will enable it now"
-                                swapon -a
-                fi
+            echo "vm.swappiness appears enabled"
         else
-            echo "no swap found in fstab we will now create and enable a swapfile"
-            /usr/bin/fallocate -l 4G /swapfile
-            /bin/chmod 600 /swapfile
-            /sbin/mkswap /swapfile
-            /sbin/swapon /swapfile
-            echo '/swapfile none swap sw 0 0' >> /etc/fstab
-fi
-
-#
-###     setup sysctl    ### 
-#
-
-if cat /etc/sysctl.conf | grep -q vm.swappiness
-    then
-        echo "vm.swappiness found in sysctl.conf "
-        if sysctl -a | grep -q swappiness
-            then 
-                echo "vm.swappiness appears enabled" 
-            else 
-                echo "vm.swappiness appears disabled we will enable it " 
-                /sbin/sysctl vm.swappiness=10
-        fi
-    else 
-        echo "vm.swappiness was not found in sysctl.conf we will add and enable it now"
-        echo 'vm.swappiness=10' >> /etc/sysctl.conf
-        /sbin/sysctl vm.swappiness=10
+            echo "vm.swappiness appears disabled we will enable it "
+            /sbin/sysctl vm.swappiness=10
+    fi
+else
+    echo "vm.swappiness was not found in sysctl.conf we will add and enable it now"
+    echo 'vm.swappiness=10' >> /etc/sysctl.conf
+    /sbin/sysctl vm.swappiness=10
 fi
 
 
-if cat /etc/sysctl.conf | grep -q vm.vfs_cache_pressure
-    then
-        echo "vm.vfs_cache_pressure found in sysctl.conf "
-        if sysctl -a | grep -q vm.vfs_cache_pressure
-            then 
-                echo "vm.vfs_cache_pressure appears enabled" 
-            else 
-                echo "vm.vfs_cache_pressure appears disabled we will enable it " 
-                /sbin/sysctl vm.vfs_cache_pressure=50
-        fi
-    else 
-        echo "vm.vfs_cache_pressure was not found in sysctl.conf we will add and enable it now"
-        echo 'vm.vfs_cache_pressure=50' >> /etc/sysctl.conf
-        /sbin/sysctl vm.vfs_cache_pressure=50
+if grep -q vm.vfs_cache_pressure /etc/sysctl.conf; then
+    echo "vm.vfs_cache_pressure found in sysctl.conf "
+    if  sysctl -a &> /dev/stdout | grep -q vm.vfs_cache_pressure
+        then
+            echo "vm.vfs_cache_pressure appears enabled"
+        else
+            echo "vm.vfs_cache_pressure appears disabled we will enable it "
+            /sbin/sysctl vm.vfs_cache_pressure=50
+    fi
+else
+    echo "vm.vfs_cache_pressure was not found in sysctl.conf we will add and enable it now"
+    echo 'vm.vfs_cache_pressure=50' >> /etc/sysctl.conf
+    /sbin/sysctl vm.vfs_cache_pressure=50
 fi
 
 #
 ###     setup the sql server enviroment (mariadb/mysql)     ###
 #
 
-if [ -s .env ] 
-    then 
-        echo "the .env file already exists and has a non zero size you should check its contents"
-        echo "you can do so with the command (nano .env) "
-    else 
-        echo "no .env file was found at .env"
-        echo "as no .env file was found we will currently assume this is the first time the kickstart script has been run "
-        echo "and so we will now also run the /usr/bin/mysql_secure_installation script to secure the sql installation "
-        echo "creating a password for the mysql root user, removing remote root access the test db and user "
-        echo "the sql root password will be needed in the next step, setting up the .env file "
-        echo ""
-        /usr/bin/mysql_secure_installation
-        echo ""
-        echo '# PUT YOUR MYSQL PASSWORD YOU JUST ENTERED BELOW, THEN PRESS CTRL+X and Y to SAVE CHANGES' >> .env
-        echo 'MYSQL_PASSWORD=changeme' >> .env
-        chmod 660 .env
-        chown root:adm .env
-        nano .env
-        echo ""        
+if [ -s .env ]; then
+    echo "The .env file already exists and has a non zero size you should check its contents"
+else
+    echo "Launching /usr/bin/mysql_secure_installation script to secure the database installation"
+    /usr/bin/mysql_secure_installation
+    echo -e "\n"
+    read -ep "Re-enter the root DB password from above: " DB_PWD
+    echo MYSQL_PASSWORD=$DB_PWD > .env
+    chmod 660 .env
+    chown root:adm .env
 fi
 
-echo ""
-echo "all initial package install tasks have completed" 
-echo "it is now time to run genie amd perform initial configuration"
-echo ""
-# eof
+echo -e "\nAll initial package install tasks have completed."
+echo -e "Now run './genie' to configure FreeRADIUS 3\n"
